### ISSUE TITLE
Expose half feature

### ISSUE THREAD

**Issue by mpetri** [zommiommy/mem_dbg-rs#2]
Can you expose the `half` feature in the cargo.toml?

**Comment by zommiommy** [comment]
If I'm correct, it's not needed. [The Cargo book says](https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies):
```
[dependencies]
gif = { version = "0.11.1", optional = true }
```
> By default, this optional dependency implicitly defines a feature that looks like this:
```
[features]
gif = ["dep:gif"]
```

so you should be able to just use the `half` feature even if I didn't define it explicitly.

If it doesn't work I'm happy to help figure it out!

**Comment by mpetri** [comment]
Ah ok. I think I'm not using 0.2 thanks!
